[package]
name = "io-arrays"
version = "0.3.1-alpha.0"
description = "Random-access I/O"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["io"]
categories = ["rust-patterns"]
repository = "https://github.com/sunfishcode/io-arrays"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.3"

[dependencies]
async-std = { version = "1.9.0", optional = true }
cap-fs-ext = "0.13.7"
cap-std = { version = "0.13.7", optional = true }
cap-async-std = { version = "0.13.7", optional = true }
io-streams = { version = "0.3.0", optional = true }
system-interface = "0.6.3"
unsafe-io = { version = "0.6.2" }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
page_size = "0.4.2"
unsafe-io = { version = "0.6.1", features = ["os_pipe"] }

[target.'cfg(not(any(target_os = "android", target_os = "linux")))'.dependencies]
tempfile = "3.2.0"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.87"
posish = "0.6.1"

[target.'cfg(windows)'.dependencies]
winx = "0.23.0"

[dev-dependencies]
anyhow = "1.0.38"
cap-tempfile = "0.13.7"
cap-std = "0.13.7"

[features]
default = ["io-streams"]

[badges]
maintenance = { status = "actively-developed" }
